/*
ES6 NEW FEATUURES
1.LET , CONST
2.~${}- STRING LITERAL [ READ VARIABLE IN THE FORM OF STRING]
3.()=>{}
4.CLASS
5.[1,2,3].FOREACH(()=>{})
        MAP(()=>{})
            FILTER
            REDUCE
            FIND
6.SPREAD 
  REST      
7.DESTRUCTURING-OJECT,ARRAY
8.IMPORT/EXPORT 
9.ASYNCHRONOUS PROS 
10.SET CLASS       */